### ISSUE TITLE
TypeError with sphericalNvector.triangulate

### ISSUE THREAD

**Issue by pvezid** [mrJean1/PyGeodesy#5]
Hello,

Thanks for putting this package together.

I have a TypeError using triangulate:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from geodesy import sphericalNvector
from geodesy.sphericalNvector import LatLon

basse_castouillet = LatLon("47°18.228'N","002°34.326'W")
basse_hergo = LatLon("47°18.664'N","002°31.717'W")

p0 = sphericalNvector.triangulate(basse_castouillet, 7, basse_hergo, 295)
print(str(p0))
```
I am getting:
```
Traceback (most recent call last):
  File "./t1.py", line 10, in <module>
    p0 = sphericalNvector.triangulate(basse_castouillet, 7, basse_hergo, 295)
  File "/Users/user/PyGeodesy/geodesy/sphericalNvector.py", line 712, in triangulate
    return Nvector(i.x, i.y, i.z).toLatLon(height=h, datum=point1.datum)
TypeError: toLatLon() got an unexpected keyword argument 'datum'
```
The package tests are running fine, am I using the package the right way ?

**Comment by mrJean1** [comment]
You're using the package correctly and found a bug.  That has been fixed and I've added your example as another test case.  Grand merci!

You could also use the `LatLon.triangulate` method, as follows:

```
    from geodesy.sphericalNvector import LatLon
    basse_castouillet = LatLon("47°18.228'N","002°34.326'W")
    basse_hergo = LatLon("47°18.664'N","002°31.717'W")
    p0 = basse_castouillet.triangulate(7, basse_hergo, 295)
```
There is no need to import the `sphericalNvector` module to get the `triangulate` function.

**Comment by mrJean1** [comment]
Closing this issue.  Please reopen if needed.
