### ISSUE TITLE
Utm Error |  pygeodesy.mgrs.MGRSError: band (''): MISSING

### ISSUE THREAD

**Issue by CaipiDE** [mrJean1/PyGeodesy#63]
Hello there, 

executing `pygeodesy.Utm(32, 'N', 280000.0, 5653000.0).toMgrs()` gives the following Error while the User cant have impact on it... The coordinates used are valid when executing a convert online on a random website. Is there anything I am doing wrong?

Traceback (most recent call last):
  File "C:/Users/Caipi/PycharmProjects/NRW/cutter.py", line 45, in <module>
    tile()
  File "C:/Users/Caipi/PycharmProjects/NRW/cutter.py", line 28, in tile
    pygeodesy.Utm(32, 'N', latitude, longitude).toMgrs()
  File "C:\Users\Caipi\PycharmProjects\pythonProject\venv\lib\site-packages\pygeodesy\utm.py", line 507, in toMgrs
    return self._mgrs if center in (False, 0, _0_0) else (
  File "C:\Users\Caipi\PycharmProjects\pythonProject\venv\lib\site-packages\pygeodesy\props.py", line 173, in __get__
    return self._fget(inst)
  File "C:\Users\Caipi\PycharmProjects\pythonProject\venv\lib\site-packages\pygeodesy\props.py", line 98, in _fget
    inst.__dict__[self.name] = val = self.method(inst)
  File "C:\Users\Caipi\PycharmProjects\pythonProject\venv\lib\site-packages\pygeodesy\utm.py", line 360, in _mgrs
    return _toMgrs(self)
  File "C:\Users\Caipi\PycharmProjects\pythonProject\venv\lib\site-packages\pygeodesy\utm.py", line 689, in _toMgrs
    return toMgrs(utm, datum=utm.datum, name=utm.name)
  File "C:\Users\Caipi\PycharmProjects\pythonProject\venv\lib\site-packages\pygeodesy\mgrs.py", line 493, in toMgrs
    r = Mgrs(utm.zone, en, e, n, **kwds)
  File "C:\Users\Caipi\PycharmProjects\pythonProject\venv\lib\site-packages\pygeodesy\mgrs.py", line 119, in __init__
    self._zone, self._band, self._bandLat = _to3zBlat(zone, band, MGRSError)
  File "C:\Users\Caipi\PycharmProjects\pythonProject\venv\lib\site-packages\pygeodesy\utm.py", line 173, in _to3zBlat
    raise Error(band=band, txt=MISSING)
pygeodesy.mgrs.MGRSError: band (''): MISSING

Process finished with exit code 1

**Comment by mrJean1** [comment]
When specifying the `Utm.zone` zone as `int`, the longitudinal band must be given as keyword argument `band='C'...'X'`, for example
```
  pygeodesy.Utm(32, 'N', 280000.0, 5653000.0, band='X').toMgrs()
```
Or specify the 'Utm.zone' including the `band` as `str` containing zone and band, like
```
  pygeodesy.Utm('32X', 'N', 280000.0, 5653000.0).toMgrs()
```
Note, band 'X' is just an example.

**Comment by mrJean1** [comment]
[PyGeodesy 21.11.10](https://pypi.org/project/PyGeodesy/21.11.10/) contains the updated `Etm`, `Utm` and `Ups` classes as described above.  The example now produces the following
```
>>> import pygeodesy
>>> u = pygeodesy.Utm(32, 'N', 280000.0, 5653000.0)
>>> u.band
'U'

>>> m = u.toMgrs()
>>> type(m)
<class 'pygeodesy.mgrs.Mgrs'>

>>> repr(m)
'[Z:32U, G:KB, E:80000, N:53000]'

>>> str(m)
'32U KB 80000 53000'

>>> u.toLatLon()
LatLonDatum5Tuple(lat=50.986484, lon=5.865326, datum=Datum(name='WGS84', ...), convergence=-2.436605, scale=1.000194)

>>> m.toLatLon()
LatLonDatum5Tuple(lat=50.986484, lon=5.865326, datum=Datum(name='WGS84', ...), convergence=-2.436605, scale=1.000194)

>>> pygeodesy.version
'21.11.10'
```
and has been added as a regression test.

Please verify and close the issue if resolved.

Thank you for reporting and providing an example of the problem.
