### ISSUE TITLE
Install error 'geodesy/sphere.pyx' doesn't match any files

### ISSUE THREAD

**Issue by lucazav** [mrJean1/PyGeodesy#75]
I'm trying to install geodesy in a Conda environment using Python 3.9.15 with a simple `pip install geodesy`.
First, it asked for installing the Cython module. I did so and I installed Cython 0.29.35.
Then I run pip install again and I got this error:

> Collecting geodesy
>   Using cached geodesy-1.1.tar.gz (172 kB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [12 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "C:\Users\lucazav\AppData\Local\Temp\2\pip-install-yj5si3t_\geodesy_815a5bb3b1b54090b433fc18466982e5\setup.py", line 38, in <module>
>           ext_modules=cythonize(extensions),
>         File "C:\ProgramData\Miniconda3\envs\pbi_powerquery_env\lib\site-packages\Cython\Build\Dependencies.py", line 973, in cythonize
>           module_list, module_metadata = create_extension_list(
>         File "C:\ProgramData\Miniconda3\envs\pbi_powerquery_env\lib\site-packages\Cython\Build\Dependencies.py", line 816, in create_extension_list
>           for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
>         File "C:\ProgramData\Miniconda3\envs\pbi_powerquery_env\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
>           raise ValueError(error_msg)
>       ValueError: 'geodesy/sphere.pyx' doesn't match any files
>       [end of output]

I'm on a Windows Server 2022.

Am I doing something wrong?

**Comment by lucazav** [comment]
Sorry, my fault. It is PyGeodesy, not geodesy!
