### ISSUE TITLE
Pygeodesy / Skops incompatibilty due to Lazy loading 

### ISSUE THREAD

**Issue by user-11** [mrJean1/PyGeodesy#76]
When Pygeodesy is installed, it causes errors when skops is imported unless Pygeodesy's Lazy loading is explicitly disabled.

Skops performs a scan looking for certain object types, and when attempting to identify the appropriate module for type, scans all loaded modules for that type, using `getattr` and expecting `AttributeError` to be raised if the type doesn't exist. 

While technically the issue is with skops, it's caused by Pygeodesy raising a `LazyImportError` instead of an `AttributeError` when attempting to load a module that doesn't exist unless lazy importing is disabled. 

Simple demonstration, using versions:

```
PyGeodesy==23.6.12
skops==0.8.0
```
```shell
Python 3.9.9 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygeodesy
>>> import skops.io
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.pyenv/versions/pygeodesy_skops_test/lib/python3.9/site-packages/skops/io/__init__.py", line 1, in <module>
    from ._persist import dump, dumps, get_untrusted_types, load, loads
  File "~/.pyenv/versions/pygeodesy_skops_test/lib/python3.9/site-packages/skops/io/_persist.py", line 22, in <module>
    module = importlib.import_module(module_name, package="skops.io")
  File "~/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "~/.pyenv/versions/pygeodesy_skops_test/lib/python3.9/site-packages/skops/io/_general.py", line 16, in <module>
    from ._trusted_types import (
  File "~/.pyenv/versions/pygeodesy_skops_test/lib/python3.9/site-packages/skops/io/_trusted_types.py", line 17, in <module>
    SCIPY_UFUNC_TYPE_NAMES = get_public_type_names(module=scipy.special, oftype=np.ufunc)
  File "~/.pyenv/versions/pygeodesy_skops_test/lib/python3.9/site-packages/skops/io/_utils.py", line 230, in get_public_type_names
    {
  File "~/.pyenv/versions/pygeodesy_skops_test/lib/python3.9/site-packages/skops/io/_utils.py", line 234, in <setcomp>
    and (type_name := get_type_name(obj)).startswith(module_name)
  File "~/.pyenv/versions/pygeodesy_skops_test/lib/python3.9/site-packages/skops/io/_utils.py", line 179, in get_type_name
    return f"{get_module(t)}.{t.__name__}"
  File "~/.pyenv/versions/pygeodesy_skops_test/lib/python3.9/site-packages/skops/io/_utils.py", line 86, in get_module
    return whichmodule(obj, obj.__name__)
  File "~/.pyenv/versions/pygeodesy_skops_test/lib/python3.9/site-packages/skops/io/_utils.py", line 49, in whichmodule
    if _getattribute(module, name)[0] is obj:
  File "~/.pyenv/versions/pygeodesy_skops_test/lib/python3.9/site-packages/skops/io/_utils.py", line 24, in _getattribute
    obj = getattr(obj, subpath)
  File "~/.pyenv/versions/pygeodesy_skops_test/lib/python3.9/site-packages/pygeodesy/lazily.py", line 564, in __getattr__
    raise LazyImportError(t, txt=_DOT_(parent, name))
pygeodesy.lazily.LazyImportError: no module or attribute: pygeodesy.agm
```

--------------------

```
Python 3.9.9 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import skops.io
>>> import pygeodesy
>>> quit()
```

--------------------

```
Python 3.9.9 (main, Dec 24 2021, 12:53:35) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ["PYGEODESY_LAZY_IMPORT"]=""
>>> import pygeodesy
>>> import skops.io
>>> quit()
```

**Comment by mrJean1** [comment]
Does it help if `LazyImportError` were a subclass of `AttributeError` instead of or in addition to `ImportError`?

**Comment by user-11** [comment]
That might do it, but I think the real issue is that `LazyImportError` has ambiguous meaning, it means either that the lazy import failed due to something related to the lazy import system itself, or that the thing doesn't exist. 

In `_lazy_import2#__getattr__`, I think it should probably just raise `AttributeError` if the name isn't in `imports` (which I believe contains all possible imports.  

So `pygeodesy.lazily` 562-564 would change from
```python
        else:  # PYCHOK no cover
            t = _no_(_module_, _or_, _attribute_)
            raise LazyImportError(t, txt=_DOT_(parent, name))
```

to

```python
        else:  # PYCHOK no cover
            t = _no_(_module_, _or_, _attribute_)
            raise AttributeError(t, txt=_DOT_(parent, name))
```

But I haven't tested anything yet, for some reason the repo takes >5GB  to clone.

**Comment by mrJean1** [comment]
Thank you for trying.  Lines 564 and 557 should raise an `AttributeError` instead of a `LazyImportError`.

Use `git  clone —depth 1 …` to get a minimal copy.

**Comment by mrJean1** [comment]
If this issue has been resolved, please close it.
